### ISSUE TITLE
Deploy somewhere so people can play with it online with zero setup

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-camp-tutorial#2]
:heart: :100: 

The reason why we would like to deploy this app is that @patriciagarcia is doing a 1h training session at http://hackinghealth.ca/event/hacking-health-camp/

<img width="1160" alt="screen shot 2016-03-12 at 12 44 09" src="https://cloud.githubusercontent.com/assets/39992/13724339/2da16d08-e850-11e5-8b3b-0d988147ce7a.png">

**Comment by girvo** [comment]
I'll gladly put my hand up for this is no-one else has :smile:

**Comment by NickColley** [comment]
Recommend using https://surge.sh/ for this :)

**Comment by gr2m** [comment]
@girvo thanks, that’d be awesome!

@nickcolley we need Node.jS and CouchDB. I think surge.sh is for static sites only?

**Comment by gr2m** [comment]
[Till suggested](https://twitter.com/klimpong/status/708643055096741888) to look how the open source Parse does it, with the deploy buttons:
- https://github.com/ParsePlatform/parse-server#parse-server-sample-application
- https://github.com/ParsePlatform/parse-server-example

**Comment by NickColley** [comment]
@gr2m I wrote that comment before checking the tutorial out sorry :)

**Comment by gr2m** [comment]
please join me with all your :clap: – @christophwitzko did it via https://github.com/hoodiehq/hoodie-camp-tutorial/pull/4
