### ISSUE TITLE
Clicking cancel when adding a color still adds a color

### ISSUE THREAD

**Issue by kkchu791** [hoodiehq/hoodie-camp-tutorial#28]
On page 6 under Add New Color,
clicking on the `add color` button and clicking cancel will add a null color. It is still adding an object even if we're not intending to.

**Comment by kkchu791** [comment]
This appears to be an issue with the hoodie-client implementation which takes it's implementation from the hoodie-store-client of hoodie.store.add(). The add function should verify that the object added is not empty.

**Comment by gr2m** [comment]
I think we should resolve this in the tutorial, not in `hoodie-store-client`. I can’t think of good use cases to create empty objects right now, but also no good reason against it. But hoodie-camp-tutorial should not run `hoodie.store.add()` in the first place if the user hits cancel. 

Do you want to try get this fixed?

**Comment by kkchu791** [comment]
I can't recreate this issue any longer. Might of been just a one time thing.

**Comment by gr2m** [comment]
okay :) thanks
